In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('manga.csv')
df.head()

,anime_id,name,genre,type,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Manga,9.37,200630
1,15335,Gintama Manga: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Manga,9.10,72534
2,28851,Koe no Katachi,"Drama, School, Shounen",Manga,9.05,102733
3,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Manga,8.93,466254
4,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Manga,8.84,226193

In [3]:
def drop_columns(df):
    # Drop specified columns from the DataFrame
    columns_to_drop = ['anime_id', 'types', 'episodes', 'rating']
    df = df.drop(columns=columns_to_drop, errors='ignore')
    return df

In [5]:
df = drop_columns(df)
df.head()

,name,genre,type,members
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Manga,200630
1,Gintama Manga: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Manga,72534
2,Koe no Katachi,"Drama, School, Shounen",Manga,102733
3,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Manga,466254
4,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Manga,226193